name: Lint and Build Package

on:
    pull_request:
        branches:
            - develop
            - main
            - "v[0-9]+.[0-9]+.[0-9]+*beta*"
        types: [opened, synchronize]

jobs:
    check_pr:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  fetch-depth: 0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Lint
              run: yarn lint
            - name: Installation & Build Package
              # installation already takes care of calling prepare which calls build
              # for the sdk package
              run: yarn --frozen-lockfile && yarn build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
